# Generated by Django 4.0.2 on 2022-04-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
